=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Dialogue/Dialogue.dtd
<!DOCTYPE DialogueSequence [
        <!ELEMENT DialogueSequence (BaseDialogue|CharacterDialogue)*>
        <!ELEMENT BaseDialogue (Text)>
        <!ELEMENT CharacterDialogue (Actor,Text)>
        <!ELEMENT Text (#PCDATA)>
        <!ELEMENT Actor (#PCDATA)>
        <!ATTLIST BaseDialogue bg CDATA #REQUIRED>
        <!ATTLIST CharacterDialogue bg CDATA #REQUIRED>

        ]>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/1_TutorialLevel/5_AfterAllIsSaidAndDone.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">

<DialogueSequence>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>Supervisor</Actor>
        <Text>Done already?!^1 You're doing great!</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>You</Actor>
        <Text>Thank you,^2 sir!^1 Just trying my best,^2 honestly.</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>Supervisor</Actor>
        <Text>That should be all for the day.^1 How about you go recharge while I process the information?</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>You</Actor>
        <Text>You're sure you don't need me for that?</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>Supervisor</Actor>
        <Text>Ha^2 Ha^2 Ha!^1 That's what other student workforces are there for!^1 You've done enough.</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>You</Actor>
        <Text>Wow, ok</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>You</Actor>
        <Text>(And thus,^2 I prevailed on my first day of work.^1 But what followed would be something that I will never forget...)</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/Generic/1_GenericError.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">

<DialogueSequence>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>You</Actor>
        <Text>There seems to be a problem with this statement!</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>Supervisor</Actor>
        <Text>Hmm, are you sure? That statement sounds perfectly reasonable.</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>You</Actor>
        <Text>ARGH! You're right!</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>Supervisor</Actor>
        <Text>Maybe you should ask the robot a bit more before jumping to conclusions.</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/TutorialLevel/2_FirstDayAtWork.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">
 
<DialogueSequence>
    <BaseDialogue bg="">
        <Text>Location:^1 Digital Media Lab - Headquarters</Text>
    </BaseDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>(Finally,^2 my first day at the Digital Media Lab.^1 They say only the bravest of all can participate in an experiment like this...)</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>(I hope I am prepared enough.^1 This is so exciting!)</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>Ah, there you are!^1 Took you long enough!</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>Well,^2 the Deutsche Bahn kind of doesn't expect snow in winter,^2 so the trains were late by merely...^1 120 minutes.</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>We have no time for any chit-chat.^1 They have received the order.^1 Now,^2 we need to act and we act fast.</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>Okay,^2 what is it that I should do?^2 You were so secretive in the flyer.</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>Secretive indeed.^1 It's a secret objective concerning a restaurant:^1 "The Orange Kitten".</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>Ohhh,^2 I've heard about it.^1 They make very delicious food!^1 I heard a cat walks around there?</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>Precisely.^1 We'd like to establish our own restaurant chain,^2 but to do so,^2 we'd like to figure out how they make those recipes.</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>That's why we need your service today.^1 Are you willing to take on this task?</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>Yes,^2 throw it at me.^1 What do I need to do?</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>Pay attention to the computer...</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/TutorialLevel/1_Beginning.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">
 
<DialogueSequence>
    <BaseDialogue bg="">
        <Text>Location:^1 ???</Text>
    </BaseDialogue>
    <CharacterDialogue>
        <Actor>???</Actor>
        <Text>The order has arrived^2, my lord.^1 Are we ready to begin?</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="">
        <Actor>"Lord"</Actor>
        <Text>Meow meow.^1 Meow meow meow?^2 Meow!^1 MEEEEEEEEOW!!!!</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>???</Actor>
        <Text>As you wish.^1 I shall swiftly make the preparations...</Text>
    </CharacterDialogue>
</DialogueSequence>
