=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Dialogue/Dialogue.dtd
<!DOCTYPE DialogueSequence [
        <!ELEMENT DialogueSequence (BaseDialogue|CharacterDialogue)*>
        <!ELEMENT BaseDialogue (Text)>
        <!ELEMENT CharacterDialogue (Actor,Text)>
        <!ELEMENT Text (#PCDATA)>
        <!ELEMENT Actor (#PCDATA)>
        <!ATTLIST BaseDialogue bg CDATA #REQUIRED>
        <!ATTLIST CharacterDialogue bg CDATA #REQUIRED>

        ]>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/2_TheMeowConspiracy/1_Beginning.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">
 
<DialogueSequence>
    <BaseDialogue bg="">
        <Text>Location:^1 ???</Text>
    </BaseDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>"Lord"</Actor>
        <Text>Meow meow.^1 Brrrrt?</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>???</Actor>
        <Text>Yes,^2 my lord,^2 they are exquisite at performing the task.^1 The excellent candidate for your plan.</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>"Lord"</Actor>
        <Text>Meoooow meow.^1 Meow.</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>???</Actor>
        <Text>Very well,^2 I shall rally the council.^1 We may begin discussions.</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/TutorialLevel/Beginning.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">
 
<DialogueSequence>
    <BaseDialogue bg="">
        <Text>Location: ???</Text>
    </BaseDialogue>
    <CharacterDialogue>
        <Actor>???</Actor>
        <Text>The order has arrived, my lord. Are we ready to begin?</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="">
        <Actor>"Lord"</Actor>
        <Text>Meow meow. Meow meow meow? Meow! MEEEEEEEEOW!!!!</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>???</Actor>
        <Text>As you wish. I shall swiftly make the preparations...</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/TutorialLevel/3_FirstSequenceDone.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">

<DialogueSequence>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>Hmm, the problem becomes apparant.</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="">
        <Actor>You</Actor>
        <Text>Popsicles are supposed to be cold. Yet the robot heats them up? Why?</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>It makes no sense. And therein lies the mistake the robot made!</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>You're right!</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/1_TutorialLevel/1_Beginning.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">
 
<DialogueSequence>
    <BaseDialogue bg="">
        <Text>Location:^1 ???</Text>
    </BaseDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>???</Actor>
        <Text>The order has arrived^2, my lord.^1 Are we ready to begin?</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>"Lord"</Actor>
        <Text>Meow meow.^1 Meow meow meow?^2 Meow!^1 MEEEEEEEEOW!!!!</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>???</Actor>
        <Text>As you wish.^1 I shall swiftly make the preparations...</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/TutorialLevel/FirstDayAtWork.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">
 
<DialogueSequence>
    <BaseDialogue bg="">
        <Text>Location: Digital Media Lab - Headquarters</Text>
    </BaseDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>(Finally, my first day at the Digital Media Lab. They say only the bravest of all can participate in an experiment like this...)</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>(I hope I am prepared enough. This is so exciting!)</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supa Visor</Actor>
        <Text>Ah, there you are! Took you long enough!</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>Well, the Deutsche Bahn kind of doesn't expect snow in winter, so the trains were late by merely... 120 minutes.</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supa Visor</Actor>
        <Text>We have no time for any chit-chat. They have received the order. Now, we need to act and we act fast.</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>Okay, what is it that I should do? You were so secretive in the flyer.</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supa Visor</Actor>
        <Text>A special assignment, a special case. We successfully infiltrated a robot at this restaurant "The Orange Kitten".</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>Ohhh, I've heard about it. They make very delicious food! One time, I ate so much, I actually vom-</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supa Visor</Actor>
        <Text>TOO. MANY. DETAILS!!</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supa Visor</Actor>
        <Text>Regardless, you are here today to work with the robot we've infiltrated there. We need to know the secret behind the tasty recipes.</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/TutorialLevel/4_ButThereIsMore.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">

<DialogueSequence>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>I believe there are still problems to be solved,^2 though...</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>And I'm not even talking about logical mistakes the robot has made,^2 but rather...</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>... unusual steps the robot took.^1 Maybe you should ask about those next.</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/1_TutorialLevel/4_ButThereIsMore.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">

<DialogueSequence>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>Supervisor</Actor>
        <Text>I believe there are still problems to be solved,^2 though...</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>Supervisor</Actor>
        <Text>And I'm not even talking about logical mistakes the robot has made,^2 but rather...</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>Supervisor</Actor>
        <Text>... unusual steps the robot took.^1 Maybe you should ask about those next.</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>Supervisor</Actor>
        <Text>After all,^2 we need to make sure not to copy those steps in the end.^1 Understood?</Text>
    </CharacterDialogue>
    <CharacterDialogue bg="" curr_portrait="">
        <Actor>You</Actor>
        <Text>Very well,^2 what do I need to do?</Text>
    </CharacterDialogue>
</DialogueSequence>

=== Javahase/the-orange-kitten/the-orange-kitten/Assets/Resources/Levels/TutorialLevel/3S_NotQuiteRight.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DialogueSequence SYSTEM "Dialogue.dtd">

<DialogueSequence>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>There seems to be a problem with this statement!</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>Hmm, are you sure? That statement sounds perfectly reasonable.</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>You</Actor>
        <Text>ARGH! You're right!</Text>
    </CharacterDialogue>
    <CharacterDialogue>
        <Actor>Supervisor</Actor>
        <Text>Think about what you learned so far. Are the conditions under which this dish was made truly okay?</Text>
    </CharacterDialogue>
</DialogueSequence>
